In [1]:
import numpy as np
import pandas as pd
# import pandas_datareader as pdr Not working
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt

from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
#layers
from tensorflow.keras.layers import Dense, Dropout, LSTM

In [9]:
#Reading in data and scaling it
import yfinance as yf

ticker = yf.Ticker("AMD")
start_date = dt.datetime(2005,1,1).strftime('%Y-%m-%d')
end_date = dt.datetime(2015,1,1).strftime('%Y-%m-%d')


data = ticker.history(start=start_date, end=end_date)

scaler = MinMaxScaler(feature_range=(0, 1))

scaled_data = scaler.fit_transform(data['Close'].values.reshape(-1,1))
scaled_data

array([[0.48660051],
       [0.45682382],
       [0.44540945],
       ...,
       [0.02133995],
       [0.02059554],
       [0.02158809]])

In [34]:
np.set_printoptions(threshold=3, linewidth=100)

timeSteps = 60

x_train = []
y_train = []

for i in range(timeSteps, len(scaled_data)):
    x_train.append(scaled_data[i-timeSteps:i, 0])
    y_train.append(scaled_data[i, 0])

x_train, y_train = np.array(x_train), np.array(y_train)

print(x_train.shape)
print(y_train.shape)
x_train

(2457, 60)
(2457,)


array([[0.48660051, 0.45682382, 0.44540945, ..., 0.33920598, 0.33796528, 0.35756823],
       [0.45682382, 0.44540945, 0.44466501, ..., 0.33796528, 0.35756823, 0.35533502],
       [0.44540945, 0.44466501, 0.44962781, ..., 0.35756823, 0.35533502, 0.35707199],
       ...,
       [0.0394541 , 0.03970224, 0.03870968, ..., 0.02158809, 0.02109182, 0.02109182],
       [0.03970224, 0.03870968, 0.03672457, ..., 0.02109182, 0.02109182, 0.02133995],
       [0.03870968, 0.03672457, 0.03672457, ..., 0.02109182, 0.02133995, 0.02059554]])

In [35]:
#reshape x_train for LSTM
x_train_reshaped = x_train.reshape(x_train.shape[0], x_train.shape[1], 1)
print(x_train_reshaped.shape)
print(x_train_reshaped)

(2457, 60, 1)
[[[0.48660051]
  [0.45682382]
  [0.44540945]
  ...
  [0.33920598]
  [0.33796528]
  [0.35756823]]

 [[0.45682382]
  [0.44540945]
  [0.44466501]
  ...
  [0.33796528]
  [0.35756823]
  [0.35533502]]

 [[0.44540945]
  [0.44466501]
  [0.44962781]
  ...
  [0.35756823]
  [0.35533502]
  [0.35707199]]

 ...

 [[0.0394541 ]
  [0.03970224]
  [0.03870968]
  ...
  [0.02158809]
  [0.02109182]
  [0.02109182]]

 [[0.03970224]
  [0.03870968]
  [0.03672457]
  ...
  [0.02109182]
  [0.02109182]
  [0.02133995]]

 [[0.03870968]
  [0.03672457]
  [0.03672457]
  ...
  [0.02109182]
  [0.02133995]
  [0.02059554]]]


In [ ]:
#Model

model = tf.keras.Sequential()